name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.4"

      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest

      - name: Run lint
        run: |
          golint examples/*.go

      - name: Run build
        run: |
          mkdir build
          for x in examples/*.go; do
            echo "BUILD $x ...""
            go build -o build/ $x
          done
